name: Go Code Check

on:
  pull_request:
    branches:
      - main

jobs:
  go-lint:
    name: Run go-lint
    runs-on: ubuntu-latest

    steps:
      # ソースコードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Go環境をセットアップ
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # 静的解析ツールをインストール
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      # 静的解析を実行
      - name: Run golangci-lint
        run: golangci-lint run ./...
